logging.level:
  org.springframework.context: DEBUG
  org.springframework.data: DEBUG
  org.springframework.jdbc: DEBUG
  example: DEBUG

spring:

  mvc:
    locale: en_US

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: none

#  sql:
#    init:
#      mode: always