logging.level:
  org.springframework.data: DEBUG
  org.springframework.jdbc: DEBUG

spring:

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: none

#  sql:
#    init:
#      mode: always